config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/users/sign_out' => 'devise/sessions#destroy'
  

  resources :bloodbanks
  get 'aboutus/index'
  get 'contactus/index'

  get 'search', to: 'search#index'
  get 'search/resuts', to: 'search#results'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  
  resources :home
  resources :donor
  resources :contactus
  resources :bloodbank
  resources :search

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bloodbank.rb
class Bloodbank < ApplicationRecord

    has_many :donors

    before_save { availability.upcase! }
    
    validates :name, presence: true, length: {maximum: 100}
    validates :address, presence: true, length: {maximum: 200}
    validates :category, presence: true
    validates :availability, presence: true, length: {maximum: 100}
   

end

app/models/donor.rb
class Donor < ApplicationRecord
    
    belongs_to :bloodbank


    before_save { email.downcase! }
    
    validates :name, presence: true, length: {maximum: 30}
    validates :bloodgroup, presence: true, length: {maximum: 3}
    validates :dateofbirth, presence: true
    validates :location, presence: true, length: {maximum: 100}
    validates :contact, presence: true, length: {minimum: 10, maximum: 10}
    validates :email, presence: true, length: {maximum: 30}


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/aboutus_controller.rb
class AboutusController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

app/controllers/bloodbanks_controller.rb
class BloodbanksController < ApplicationController
  before_action :authenticate_user!   
  before_action :set_bloodbank, only: %i[ show edit update destroy ]
  

  # GET /bloodbanks or /bloodbanks.json
  def index
    # @bloodbanks = Bloodbank.all
    @bloodbanks= Bloodbank.paginate(page: params[:page], per_page:4 )
  end

  # GET /bloodbanks/1 or /bloodbanks/1.json
  def show
    
  end

  # GET /bloodbanks/new
  def new
    @bloodbank = Bloodbank.new
  end

  # GET /bloodbanks/1/edit
  def edit
  end

  # POST /bloodbanks or /bloodbanks.json
  def create
    @bloodbank = Bloodbank.new(bloodbank_params)

    respond_to do |format|
      if @bloodbank.save
        format.html { redirect_to @bloodbank, notice: "Bloodbank was successfully created." }
        format.json { render :show, status: :created, location: @bloodbank }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bloodbank.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bloodbanks/1 or /bloodbanks/1.json
  def update
    respond_to do |format|
      if @bloodbank.update(bloodbank_params)
        format.html { redirect_to @bloodbank, notice: "Bloodbank was successfully updated." }
        format.json { render :show, status: :ok, location: @bloodbank }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bloodbank.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bloodbanks/1 or /bloodbanks/1.json
  def destroy
    @bloodbank.destroy
    respond_to do |format|
      format.html { redirect_to bloodbanks_url, notice: "Bloodbank was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bloodbank
      @bloodbank = Bloodbank.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bloodbank_params
      params.require(:bloodbank).permit(:name, :address, :category, :availability)
    end
end

app/controllers/contactus_controller.rb
class ContactusController < ApplicationController
  def index
  end
end

app/controllers/donor_controller.rb
class DonorController < ApplicationController
    before_action :authenticate_user!     

    def show
        @donor=Donor.find(params[:id])
    end    

    def index
        @donor= Donor.paginate(page: params[:page], per_page:4 )
    end 
    
    
    def new
        @donor=Donor.new

    
    end


    def create
        @donor=Donor.new(params.require(:donor).permit(:name,:bloodgroup,:dateofbirth,:location,:contact,:email,:bloodbank_id))
        
        if @donor.save
            # flash[:notice]="New Donor is added successfully!!"
            redirect_to donor_index_path, notice: "New Donor is added successfully!!"

        else
            redirect_to new_donor_path
        end  
        # save those details
    end    

    

    def edit
        #create the form with details
        @donor=Donor.find(params[:id])
    end

    
    def update
        @donor=Donor.find(params[:id])
        @donor.update(params.require(:donor).permit(:name,:bloodgroup,:dateofbirth,:location,:contact,:email,:bloodbank_id))
        @donor.save
        redirect_to donor_path
        #save the new details 
    end


    def destroy
        @donor=Donor.find(params[:id])
        @donor.destroy
        redirect_to donor_index_path

    end    

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
    
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
    before_action :authenticate_user!
 
    def index
    end

    def results
        @donor = Donor.where('name LIKE ?', "%#{params[:q]}%")
    end
end

app/helpers/aboutus_helper.rb
module AboutusHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bloodbanks_helper.rb
module BloodbanksHelper
end

app/helpers/contactus_helper.rb
module ContactusHelper
end

app/helpers/donor_helper.rb
module DonorHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/aboutus/index.html.erb
<br>
<div class="jumbotron" >
<h2><u>A Centralized Blood Bank Management System</u></h2>
</div>


<h5 >Online blood bank enforces Drug & Cosmetic Act, National blood policy standards and guidelines ensuring proper collection & donation, effective management and monitoring the quality and quantity of the donated blood. </h5>
<br><br>
<h5>Our blood bank has four major components for management of the blood donation life cycle:</h5>
<br>
<ul>

<li>The bio metric Donor Management System for identifying, tracking and blocking donors based on donors health, donation history etc.

<li>It provides features such as blood grouping, TTI screening, antibody screening, component preparation etc. as per the defined processes and rules.

<li>A centralized Blood Inventory Management System for keeping track of the blood stock across numerous blood banks.

<li>Bio-Medical Waste Management System for disposal of discarded blood and other waste generated during this process.


</ul>

app/views/bloodbanks/_form.html.erb
<%= form_with(model: bloodbank, local: true) do |form| %>


  <% if bloodbank.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bloodbank.errors.count, "error") %> prohibited this bloodbank from being saved:</h2>

      <ul>
        <% bloodbank.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <br>
    <%= form.text_field :name, placeholder:"Enter blood bank name here", class:"form-control form-row col-md-5 mb-3" %>
<br>
    <%= form.text_area :address, size: "30x5", placeholder: "Enter Address of blood bank here", class: "form-control form-row col-md-5 mb-3", required: true%><br>

   
    <div class="text-white">  Select category of blood bank here : &nbsp;

      <%= form.select :category, [ 'Govt', 'Private', 'Charity'], 
      :prompt => 'Select any one', required: true   %>  
    </div>
    <br>
 
    <%= form.text_field :availability, placeholder:"Enter blood groups available in blood bank ", class:"form-control form-row col-md-5 mb-3"%>

  <br><br> 

  <%= link_to 'Back', bloodbanks_path,class: "btn btn-info" %>
  &ensp;
  <%= form.submit 'Save Details', class: "btn btn-info" %> 

  <% end %>
  

app/views/bloodbanks/edit.html.erb
<div class="container" align = "center" id="jumbo"><br>

<h2 class="text-white"><u> Update Blood Bank Details</u></h2>
<br>


<%= render 'form', bloodbank: @bloodbank %>

<br><br><br>
</div>

app/views/bloodbanks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blood Banks</h1>
<br>
<table class="table bg-white" id="tablecss" >
  <thead class="thead-dark bg-dark" align="center" >
    <tr>
      <th scope="col">Blood Bank Name</th>
      <th scope="col">Available Blood Groups</th>
      <th scope="col">Action</th>
    </tr>
  </thead>

  <tbody align="center" >
    <% @bloodbanks.each do |bloodbank| %>
      <tr>
        <td><%= bloodbank.name %></td>
        <td><%= bloodbank.availability %></td>
        <td><%= link_to 'View More', bloodbank,  class: "btn btn-success" %>

      </tr>
    <% end %>
  </tbody>
</table>
<br>

<div class="flickr_pagination">
<%= will_paginate @bloodbanks %>
</div>


<%= link_to 'New Bloodbank', new_bloodbank_path, class: "btn btn-outline-danger" %>
<br>
<br>

app/views/bloodbanks/new.html.erb
<div class="container" align = "center" id="jumbo"><br>

<h2 class="text-white"> <u> Add New Blood Bank </u> </h2> <br>

<%= render 'form', bloodbank: @bloodbank %>

<br><br><br>

</div>

app/views/bloodbanks/show.html.erb
<div class="container" align="center">
    <div class="jumbotron jumbotron-fluid"  id ="showbg">
        <p id="notice"><%= notice %></p>

        <h2><u> Blood Bank Details</u></h2>
        <br><br>

        <table align="center">
  
        <tbody>
          <tr>
            <th> &emsp; &emsp; &emsp; &emsp; NAME</th>
            <td>: &nbsp <%= @bloodbank.name%> </td>   
          </tr>
          <tr>
            <th> &emsp; &emsp; &emsp; &emsp;  ADDRESS</th>
            <td>: &nbsp <%= @bloodbank.address %> </td>
          </tr>
          <tr> 
            <th> &emsp; &emsp; &emsp; &emsp;   CATEGORY</th>
            <td>: &nbsp <%= @bloodbank.category %> </td>
          </tr>
          <tr>
            <th> &emsp; &emsp; &emsp; &emsp;   AVAILABILITY</th>
            <td>: &nbsp <%= @bloodbank.availability %> </td>
          </tr>
  
      </tbody>
  </table>
       
  <br><br><br>

        <%= link_to 'Edit', edit_bloodbank_path(@bloodbank), class: "btn btn-info" %> &nbsp;
        <%= link_to 'Back', bloodbanks_path,class: "btn btn-info" %>

        
        <br><br><br><br><br><br><br><br><br><br><br><br>


    </div>
</div>

app/views/contactus/index.html.erb
<div class="container">
<br><br><br>
    <h2 class="text-danger"><u>Contact Details</u></h2>  <br>
    <h4>For blood bank related queries, feedback and suggestions:</h4>
    Address: Center For Development of Advanced Computing<br>
    C-56/1, Anusandhan Bhawan , Sector-62, Noida, Uttar Pardesh-201307<br><br>
    Contact number: <a href=""> +91-8527304568</a>
    <br><br>
    E-mail us: <a href=""> ourbloodbank@cdac.in</a>
    <br><br>

   <h5> For Administrative queries:<br></h5>
    Blood Cell, National Health Mission<br>
    Ministry of Health & Family Welfare, New Delhi-110011<br>

</div>

app/views/donor/edit.html.erb
<div class="container text-white" align = "center" id="jumbo">
<br>
<h2><u>UPDATE DONOR DETAILS</u></h2>
<br><br>


<%= form_with(model: @donor, local: true) do |f| %>
    <%= f.label :Name %>
    <%= f.text_field :name, autofocus: true, class: "form-row col-md-5 mb-3" %><br>

    <div class="text-white">  Update Your Blood Group Here  : 
    <%= f.select :bloodgroup, [ 'A+', 'A-', 'B+', 'B-', 'O+','O-','AB+','AB-' ], :prompt => 'Select any one',
    class: "form-control form-row col-md-8 mb-7",required: true   %>
    <br>
    <br>
     
    <div class="text-white">  Update DOB Here : 
    <%= f.date_select(:dateofbirth, selected: Date.today, start_year: Date.today.year - 65, 
    end_year: Date.today.year - 18) %>
    <br><br><br>

    <%= f.label :Location %>
    <%= f.text_area :location,size: "30x5", class: "form-row col-md-5 mb-3" %><br>

    <%= f.label :Contact %>
    <%= f.text_field :contact, class: "form-row col-md-5 mb-3" %><br>

    <%= f.label :Email %>
    <%= f.text_field :email, class: "form-row col-md-5 mb-3" %><br>
    
   
    <div class="form-control form-row col-md-5 mb-3">
    <%= f.select(:bloodbank_id, Bloodbank.all.collect {|p| [ p.name, p.id ] }, 
    { :prompt => "Please select any on blood bank"}, ) %>
    </div>

    <%= link_to 'Back', donor_path,class: "btn btn-info" %>  &nbsp;
    <%= f.submit "Update", class: "btn btn-info" %>



<% end %>    

<br>  <br>
</div>

app/views/donor/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Donors</h1>

<table class="table"  id="tablecss">
  <thead class="thead-dark bg-dark" align="center" >
    <tr>
      <th scope="col">NAME</th>
      <th scope="col">BLOOD GROUP</th>
      <th scope="col"> Blood Bank Donated To </th>

      <th scope="col">Actions</th>
    </tr>
  </thead>

  <tbody align="center" >
  <% @donor.each do |i| %>
    <tr>
      <td><%= i.name %></td>
      <td><%= i.bloodgroup %></td>
      <td><%= i.bloodbank.name %></td>
     
      <td><%= link_to 'View More', donor_path(i), class: "btn btn-success" %> 

      </td> &nbsp;
    </tr>
  <% end %>
  </tbody>
</table>


    <div class="flickr_pagination">
      <%= will_paginate @donor %>
    </div>
<br>


<%= link_to 'New Donor',new_donor_path, class: "btn btn-outline-danger" %>
<br><br>

app/views/donor/new.html.erb
<div class="container" align = "center" id="jumbo"><br>
    
    <h2 class="text-white"> <u> Add New Donor </u> </h2> <br>
    
        <%= form_with scope: :donor, url: donor_index_path, local: true do |f| %>
          
        <%= f.text_field :name, autofocus: true,placeholder: "Enter your name here", class: "form-control form-row col-md-5 mb-3",required: true %><br>  

        <div class="text-white">  Select Your Blood Group Here  : &emsp; &emsp; &nbsp;
        <%= f.select :bloodgroup, [ 'A+', 'A-', 'B+', 'B-', 'O+','O-','AB+','AB-' ], 
        :prompt => 'Select any one', required: true   %>
        </div>

        <br><br>

        <div class="text-white">  Enter Date of Birth Here : &nbsp; 
        <%= f.date_select(:dateofbirth, selected: Date.today, start_year: Date.today.year - 65, 
        end_year: Date.today.year - 18) %>

        <br><br>
            
        <%= f.text_area :location, size: "30x5", placeholder: "Enter your Address here", class: "form-control form-row col-md-5 mb-3", required: true%><br>

        <%= f.number_field :contact, placeholder: "Enter your contact here", class: "form-control form-row col-md-5 mb-3",required: true %><br>

        <%= f.email_field :email, placeholder: "Enter your email here", class: "form-control form-row col-md-5 mb-3", required: true %><br>

        <div class="form-control form-row col-md-5 mb-3">
        <%= f.select(:bloodbank_id, Bloodbank.all.collect {|p| [ p.name, p.id ] }, { :prompt => "Please select any on blood bank"}, ) %>
        </div>
        <%= link_to 'Back', donor_index_path,class: "btn btn-info" %>  
        <%= f.submit :"Save Donor", class: "btn btn-info" %>

        <% end %>
  
        <br>  <br>


   

</div>  

app/views/donor/show.html.erb
<div class="container" align="center">
    <div class="jumbotron jumbotron-fluid"  id ="showbg">


    <h2><u> Donor Details</u></h2>
    <br>


    <table align="center">
  
      <tbody>
        <tr>
          <th> &emsp; &emsp; &emsp; &emsp; DONORS NAME</th>
          <td>: &nbsp <%= @donor.name %></td>   
        </tr>
        <tr>
          <th> &emsp; &emsp; &emsp; &emsp;  BLOOD GROUP </th>
          <td>: &nbsp <%= @donor.bloodgroup %></td>
        </tr>
        <tr>
          <th> &emsp; &emsp; &emsp; &emsp;   DATE OF BIRTH</th>
          <td>: &nbsp <%= @donor.dateofbirth %></td>
        </tr>
        <tr>
          <th> &emsp; &emsp; &emsp; &emsp;   LOCATION</th>
          <td>: &nbsp <%= @donor.location %></td>
        </tr>
        <tr>
        <th> &emsp; &emsp; &emsp; &emsp;  CONTACT</th>
        <td>: &nbsp <%= @donor.contact %></td>
        </tr>
        <tr>
        <th> &emsp; &emsp; &emsp; &emsp;  E-MAIL</th>
        <td>: &nbsp <%= @donor.email %></td>
        </tr>

     
        <tr>
          <th> &emsp; &emsp; &emsp; &emsp;   BLOOD BANK NAME</th>
          <td>: &nbsp <%= @donor.bloodbank.name %></td>
        </tr>
        <tr>
          <th> &emsp; &emsp; &emsp; &emsp;   BLOOD BANK ADDRESS </th>
          <td>: &nbsp <%= @donor.bloodbank.address %></td>
        </tr>
      

    </tbody>
</table>
      <br>
      <%= link_to 'Back',donor_index_path, class: "btn btn-info" %>  &nbsp;
      <%= link_to 'Edit Here', edit_donor_path,class: "btn btn-info" %>  
      <br><br> <br> <br><br> 
</div>
</div>






<% if false %>      
ID No:<%= @donor.id %><br>
NAME:<%= @donor.name %><br>
BLOOD GROUP:<%= @donor.bloodgroup %><br>
DATE OF BIRTH:<%= @donor.dateofbirth %><br>
LOCATION:<%= @donor.location %><br>
CONTACT:<%= @donor.contact %><br>
EMAIL:<%= @donor.email %><br>
<% end %>

app/views/home/index.html.erb
<%= image_tag 'home.jpg' %>


<footer class="card-footer text-light bg-dark pd-1" align="center">

    <h5 id="center">Copyright &copy; Online Blood Bank System</h6>

</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Onlinebloodbank</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Carter+One&display=swap" rel="stylesheet">
    
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Russo+One&display=swap" rel="stylesheet">


    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id="allfont">
  <div class="container" align="center">

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top" id="fontnav">
  <a class="navbar-brand mr-4" href="#"> <%= image_tag 'logo.png' %>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
      <%= link_to 'Home',root_path,class: "nav-link" %> <span class="sr-only">(current)</span></a>
      </li>
      &nbsp;
      <li class="nav-item">
      <%= link_to 'Donor',donor_index_path, class: "nav-link" %>
      </li>
      &nbsp;
    
      <li class="nav-item">
      <%= link_to 'Blood Bank',bloodbanks_path, class: "nav-link" %>
      </li>
      &nbsp;

      <li class="nav-item">
      <%= link_to 'About Us',aboutus_index_path, class: "nav-link" %>
      </li>
      &nbsp;
      <li class="nav-item">
      <%= link_to 'Contact Us',contactus_index_path ,class: "nav-link" %>
      </li>
      &nbsp;
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          My Account
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <% if user_signed_in? %>
          <%= link_to 'Logout',destroy_user_session_path ,  :method => :delete, class: "dropdown-item" %>
        <% else %>
          <%= link_to 'Signup',new_user_registration_path ,class: "dropdown-item" %>
          <%= link_to 'Login',new_user_session_path,class: "dropdown-item" %>
        <% end %>

         
        </div>
      </li>
     
    </ul>
    
    <form class="form-inline my-2 my-lg-0">
      <%= link_to 'Search', search_index_path,  class: "nav-link btn btn-danger" %>
    </form>
   
    
  </div>
</nav>
</div>
<div class="container" align="center">

<%= yield %>
</div>
  </body>
</html>

app/views/search/index.html.erb
<div class="container" align="center">
    <div class="jumbotron jumbotron-fluid text-white"  id ="jumbo">

        <h2><u>Search By Donor Name</u></h2>
        <br>

        <%= form_tag(search_resuts_path	, method: "get") do %>
        <%= label_tag(:q, "Search for:") %>
        <%= text_field_tag(:q) %>
        <br><br>
        <%= submit_tag("Search", class:"btn btn-info") %>
        <% end %>
    </div>
</div>

app/views/search/results.html.erb
<div class="container" align="center">
    <div class="jumbotron jumbotron-fluid text-white"  id ="jumbo">

        <h2>Donor Found : <%= @donor.size %></h2>


        <% if @donor.empty? %>
        <p>Sorry, no donors found.</p>
        <% else %>
        <ul type=none>
        <br>
            <% @donor.each do |donor| %>
            <li><%= link_to donor.name, donor_path(donor),  class:"btn btn-link" %></li>
            <% end %>
        </ul>
        <% end %>

    </div> 
</div>